# Generated by Django 4.1 on 2022-08-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_name', models.CharField(max_length=50)),
                ('upload_description', models.CharField(max_length=500)),
                ('upload_course_code', models.CharField(max_length=10)),
                ('upload_document', models.CharField(max_length=100)),
                ('upload_type', models.IntegerField(choices=[(0, 'تلخيص'), (1, 'شرح'), (2, 'أسئلة'), (3, 'امتحان'), (4, 'بنك اسئلة'), (5, 'ملفات اخرى'), (6, 'غيره')])),
            ],
        ),
    ]
