# Generated by Django 4.1 on 2022-08-28 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploaders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='upload',
            name='upload_document',
        ),
        migrations.CreateModel(
            name='UploadsFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploaders.files')),
                ('uploadClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploaders.upload')),
            ],
        ),
    ]
