# Generated by Django 4.1 on 2022-09-03 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uploaders', '0003_alter_upload_upload_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='directory',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='file_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
